//this module is made by XUNLOCKNETWORK DO NOT COPY
function LoadIslandModule()
{
document.write('<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>');
document.write('<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>');
document.write('<style>');
document.write('    {');
document.write('    margin: 0;');
document.write('    padding: 0;');
document.write('    box-sizing: border-box;');
document.write('    font-family: Poppins, sans-serif;');
document.write('}');
document.write('.island_TXT');
document.write('{');
document.write('    font-family: Poppins, sans-serif;');
document.write('}');
document.write('body');
document.write('{');
document.write('    display: flex;');
document.write('    justify-content: center;');
document.write('    align-items: center;');
document.write('    min-height: 100vh;');
document.write('}');
document.write('.box');
document.write('{');
document.write('    position: relative;');
document.write('    width: 300px;');
document.write('    height: 600px;');
document.write('    background: #666;');
document.write('    border-radius: 50px;');
document.write('}');
document.write('.box::before');
document.write('{');
document.write('    content: \'\';');
document.write('    position: absolute;');
document.write('    inset: 3px;');
document.write('    background: #000;');
document.write('    border-radius: 45px;');
document.write('}');
document.write('.inner');
document.write('{');
document.write('    position: absolute;');
document.write('    inset: 3px;');
document.write('    background: url("bg.jpeg");');
document.write('    background-size: cover;');
document.write('    background-position: center;');
document.write('    border-radius: 48px;');
document.write('    border: 10px solid #000;');
document.write('    display: flex;');
document.write('    justify-content: center;');
document.write('    opacity: 0;');
document.write('    transition: 0.5s;');
document.write('}');
document.write('.box:hover .inner');
document.write('{');
document.write('    opacity: 1;');
document.write('}');
document.write('.btn');
document.write('{');
document.write('    position: absolute;');
document.write('    top: 110px;');
document.write('    left: -2px;');
document.write('    width: 3px;');
document.write('    height: 26px;');
document.write('    border-top-left-radius: 4px;');
document.write('    border-bottom-left-radius: 4px;');
document.write('    background: radial-gradient(#ccc, #666, #222);');
document.write('    z-index: 10;');
document.write('}');
document.write('.btn.btn2');
document.write('{');
document.write('    top: 160px;');
document.write('    height: 40px;');
document.write('}');
document.write('.btn.btn3');
document.write('{');
document.write('    top: 220px;');
document.write('    height: 40px;');
document.write('}');
document.write('.rightSideBtn');
document.write('{');
document.write('    position: absolute;');
document.write('    top: 170px;');
document.write('    right: -2px;');
document.write('    width: 3px;');
document.write('    height: 70px;');
document.write('    border-top-right-radius: 4px;');
document.write('    border-bottom-right-radius: 4px;');
document.write('    background: radial-gradient(#ccc, #666, #222);');
document.write('    z-index: 10;');
document.write('}');
document.write('.island_popup');
document.write('{');
document.write('       position:fixed;');
document.write('    top:10px;');
document.write('    width: 90px;');
document.write('    height: 25px;');
document.write('    background: #ff0000;');
document.write('    border-radius: 20px;');
document.write('    transition: 0.5s ease-in-out;');
document.write('    display: flex;');
document.write('    justify-content: space-between;');
document.write('    align-items: center;');
document.write('}');
document.write('.island_popup:hover');
document.write('{');
document.write('    width: 200px;');
document.write('    height: 25px;');
document.write('}');
document.write('.island_popup.active');
document.write('{');
document.write('    width: 250px;');
document.write('    height: 60px;');
document.write('    border-radius: 50px;');
document.write('}');
document.write('.content');
document.write('{');
document.write('    position: relative;');
document.write('    display: flex;');
document.write('    width: 100%;');
document.write('    justify-content: space-between;');
document.write('    padding: 10px;');
document.write('    line-height: 25px;');
document.write('}');
document.write('.content p');
document.write('{');
document.write('    color: #fff;');
document.write('    font-size: 0.6em;');
document.write('    cursor: default;');
document.write('    visibility: hidden;');
document.write('    opacity: 0;');
document.write('    transition: 0.5s;');
document.write('}');
document.write('.action');
document.write('{');
document.write('    position: relative;');
document.write('    top: 5px;');
document.write('    color: #fff;');
document.write('    display: flex;');
document.write('    gap: 12px;');
document.write('    transition: 0.5s;');
document.write('    visibility: hidden;');
document.write('    opacity: 0;');
document.write('}');
document.write('.island_popup.active .action');
document.write('{');
document.write('    top: 12px;');
document.write('}');
document.write('ion-icon.red');
document.write('{');
document.write('    color: #fd443b;');
document.write('    transform: rotate(135deg);');
document.write('    cursor: pointer;');
document.write('    transition: 0.5s;');
document.write('}');
document.write('ion-icon.green');
document.write('{');
document.write('    color: #31d059;');
document.write('    cursor: pointer;');
document.write('    transition: 0.5s;');
document.write('}');
document.write('.island_popup:hover p,');
document.write('.island_popup.active p,');
document.write('.island_popup:hover .action,');
document.write('.island_popup.active .action');
document.write('{');
document.write('    visibility: visible;');
document.write('    opacity: 1;');
document.write('    transition-delay: 0.25s;');
document.write('}');
document.write('.island_popup.active ion-icon.red');
document.write('{');
document.write('   background: #fd443b;');
document.write('    color: #fff;');
document.write('    border-radius: 50px;');
document.write('    box-shadow: 0 0 0 8px #fd443b;');
document.write('    margin-right: 8px;');
document.write('}');
document.write('.island_popup.active ion-icon.green');
document.write('{');
document.write('   background: #31d059;');
document.write('    color: #fff;');
document.write('    border-radius: 50px;');
document.write('    box-shadow: 0 0 0 8px #31d059;');
document.write('    margin-right: 8px;');
document.write('}');
document.write('.details');
document.write('{');
document.write('    position: relative;');
document.write('    display: flex;');
document.write('    align-items: center;');
document.write('}');
document.write('.details .imgBx');
document.write('{');
document.write('    position: relative;');
document.write('    width: 0;');
document.write('    height: 0;');
document.write('    background: #fff;');
document.write('    border-radius: 50%;');
document.write('    overflow: hidden;');
document.write('    transition: 0.5s;');
document.write('}');
document.write('.island_popup.active .details .imgBx');
document.write('{');
document.write('    width: 40px;');
document.write('    height: 40px;');
document.write('    margin-right: 8px;');
document.write('}');
document.write('.details .imgBx img');
document.write('{');
document.write('    position: absolute;');
document.write('    top: 0;');
document.write('    left: 0;');
document.write('    width: 100%;');
document.write('    height: 100%;');
document.write('    object-fit: cover;');
document.write('}');
document.write('</style>');
document.write('<div class="island_popup">');
document.write('    <div class="content">');
document.write('                    <p class="island_TXT">Welcome To LHBOS</p>');
document.write('                </div>');
document.write('</div>');

}
LoadIslandModule();
